version: '3.8'

services:
  react-app:
    build:
      context: ../palmetto-weather-app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_NEST_API=http://localhost:4000
    depends_on:
      - nestjs-api

  nestjs-api:
    build:
      context: ../weather-api
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - NEST_APP_API_URL=https://api.openweathermap.org/data/2.5
      - NEST_APP_API_KEY=b58221879909d94cf8fa1ffce75104aa
